# This is a basic workflow to help you get started with Actions

name: CI

#on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  #workflow_dispatch:
  on: [push]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Run cmake
        run: mkdir build && cd build && cmake ..

      - name: Run build
        run: cmake --build .
        
      - name: Run test
        run: ./Debug/GTest.exe
