# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Run cmake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DNOTTEST=OFF ..

      - name: Run build
        run: cd build && cmake --build . --config Release
        
      - name: Run test
        run: build/Release/GTest.exe > run.txt && sed -n '/\[==========\] Running/,$d' readme.md && cat run.txt >> readme.md && echo \`\`\` >> readme.md && cat run.txt 
      - uses: Zizopt/techProg@master
        with:
          path: ${{ env.home }}/readme.md
          contents: |
            cat readme.md
          write-mode: overwrite
        
