# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Run cmake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DNOTTEST=OFF ..

      - name: Run build
        run: cd build && cmake --build . --config Release
        
      - name: Run test
        run: build/Release/GTest.exe > run.txt && cat run.txt
        
      - name: Writing result
        run: | 
          sed -n '/## Результаты тестов:/,$d' readme.md > newReadme.md
          echo \#\# Результаты тестов: >> newReadme.md
          echo \`\`\` >> newReadme.md
          cat run.txt >> newReadme.md
          echo \`\`\` >> newReadme.md
          cat newReadme.md > readme.md
          git config --global user.email "alexkonnov.999@mail.ru"
          git config --global user.name "Lex"
          git add readme.md
          git commit -m "Update readme.md"
          git push